<?php
    
    // set title
    $this->headTitle($this->myCustomTitle)
                    ->setSeparator(' - ')
                    ->prepend('Simple Task Manager');   
 
    // set styles    
    $this->headLink()->appendStylesheet('/css/custom.css')
                     ->prependStylesheet('/css/bootstrap-responsive.css')
                     ->prependStylesheet('/css/bootstrap.css')
                     ->headLink(array('rel' => 'favicon', 'href' => '/img/favicon.png'));

    // set scripts
    $this->headScript()->prependFile('/js/jquery-1.7.1.min.js')
                       ->appendFile('/js/bootstrap.min.js')
                       ->appendFile('/js/custom.js');
    
    // set metas
    $this->headMeta()->appendName('description', 'test zend framework project')
                     ->appendName('author', 'Alexey Udivankin')
                     ->appendName('viewport', 'width=device-width, initial-scale=1.0');
    
    // echo doctype found in application.ini
    echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    
<?php
        // echo metas
        echo $this->headMeta();
        // echo title
        echo $this->headTitle();
        // echo css array
        echo $this->headLink();
?>
    
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
    
</head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Simple Task Manager</a>
          <div class="nav-collapse">
            <ul class="nav">
	      <li><a href="/">Home</a></li>
              <li class="active">&rarr; <a href="#"><?php echo $this->myCustomTitle; ?></a></li>
            </ul>
              
<?php 

// displaying login or logout link

if ($this->userInfo) {
   echo '<p class="navbar-text pull-right">Hello, '.$this->userInfo->username.'. <a href="'.$this->url(array('controller'=>'auth', 'action'=>'logout')).'">Log out</a></p>';
} else {
   echo '<p class="navbar-text pull-right"><a href="'.$this->url(array('controller'=>'auth', 'action'=>'login')).'">Sign in</a> or <a href="'.$this->url(array('controller'=>'auth', 'action'=>'signup')).'">Sign up for Free!</a></p>';
}

?>
              
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    
     <div class="container">
<?php
            // echo view content
            echo $this->layout()->content;
?>
    </div>
    
            
<?php  
    // echo js array
    echo $this->headScript();  
?>
    
</body>
</html>
