<?php 
    $statuses = array('New','Started','Finished','Accepter','Rejected'); 
?>

<div class="modal" id="deleteCommentModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Delete confirmation</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to delete this comment?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary">Yes</a>
    <a href="#" class="btn btnModalClose">No, thanks</a>
  </div>
</div>

<div class="modal" id="deleteStoryModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Delete confirmation</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to delete this story?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary">Yes</a>
    <a href="#" class="btn btnModalClose">No, thanks</a>
  </div>
</div>

<div class="row">
    
    <div class="span2 well" style="padding: 8px 0;">
        <ul class="nav nav-list">
        <li class="nav-header">
            Filter by officer:
        </li>
        <li class="active"><a href="#">allx</a></li>
        <li><a href="#">user</a></li>
        <li class="nav-header">
            Filter by status:
        </li>
        <li><a href="#" class="filterByStatus" filterstatus="0"><?php echo $statuses[0]; ?></a></li>
        <li><a href="#" class="filterByStatus" filterstatus="1"><?php echo $statuses[1]; ?></a></li>
        <li><a href="#" class="filterByStatus" filterstatus="2"><?php echo $statuses[2]; ?></a></li>
        <li><a href="#" class="filterByStatus" filterstatus="3"><?php echo $statuses[3]; ?></a></li>
        <li><a href="#" class="filterByStatus" filterstatus="4"><?php echo $statuses[4]; ?></a></li>
        </ul>
    </div>
    
    <div class="span10">
<?php

    $this->myCustomTitle = "Stories list";

    foreach ($this->stories as $story) {
        
        $subtitle = 'Author: '.$story['content']['author'].' | Officer: '.$story['content']['officer'];
        $commentsCount = count($story['comments']);
        $currentStatusTitle = 'Mark as Started';
        
        echo '<div class="alert alert-info story" storyStatus="'.$story['content']['status'].'" storyOfficer="'.$story['content']['officer'].'" storyID="'.$story['content']['id'].'">';
        echo '<div class="storyBlock"><div class="storyBlockTitle"><h4><strong>['.$statuses[$story['content']['status']].'] #'.$story['content']['id'].'</strong> '.$story['content']['title'].'</h4></div>';
        echo '<p>'.$subtitle.'</p><p>Description: '.$story['content']['desc'].'</p>';
        
        ?>

        <div class="storyBlockRight">
            <div class="btn-group">
                <a class="btn" href="#"><?php echo $currentStatusTitle; ?></a>
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Mark as Finished</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-ok"></i> Accept</a></li>
                    <li><a href="#"><i class="icon-retweet"></i> Reject</a></li>
		    <li class="divider"></li>
		    <li><a href="#" class="deleteStory" storyID="<?php echo $story['content']['id']; ?>"><i class="icon-remove"></i> Delete Story</a></li>
                </ul>
            </div>
             <a class="btn commentbutton tooltiped" data-original-title="Toggle comments (<?php echo $commentsCount; ?>)" data-toggle="button"><i class="icon-comment"></i></a>
        </div>
       
    </div>
    <div class="storyComments">
    <?php
        foreach ($story['comments'] as $comment) {
            echo '<pre>'.$comment['author'].' wrote: '.$comment['text'].'<i class="icon-remove removeComment" title="Delete Comment" commentID="'.$comment['id'].'"></i></pre>';
        }
    
    ?>
        <textarea class="input-xlarge" id="commentTextarea<?php echo $story['content']['id']; ?>" rows="2"></textarea>
        <a class="btn addCommentBtn" storyID="<?php echo $story['content']['id']; ?>">Add comment</a>
    </div>
    
    

</div>

        <?php
    }

?>