<?php 

    $statuses = array('new','started','finished','accepted','rejected');
    
?>

<div class="modal" id="deleteCommentModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Delete confirmation</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to delete this comment?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-danger" id="btnConfirmDeleteComment">Yes</a>
    <a href="#" class="btn btnModalClose">No, thanks</a>
  </div>
</div>

<div class="modal" id="deleteStoryModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Delete confirmation</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to delete this story?</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-danger" id="btnConfirmDeleteStory">Yes</a>
    <a href="#" class="btn btnModalClose">No, thanks</a>
  </div>
</div>

<div class="modal" id="rateStoryModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Rate solution</h3>
  </div>
  <div class="modal-body">
    <p>Please rate the solution provided to this story using 1-5 star rating</p>
	<ul class="starRating"">
	    <li class="one"><a href="javascript: return false;">1</a></li>
	    <li class="two"><a href="javascript: return false;">2</a></li>
	    <li class="three"><a href="javascript: return false;">3</a></li>
	    <li class="four"><a href="javascript: return false;">4</a></li>
	    <li class="five"><a href="javascript: return false;">5</a></li>
	</ul>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-success" id="btnSetRatingAccept">Rate and Accept</i></a>
    <a href="#" class="btn btn-danger" id="btnSetRatingReject">Rate and Reject</i></a>
  </div>
</div>

<div class="row">
    
    
    <div class="span2 well" style="padding: 8px 0;">
        <ul class="nav nav-list" id="storyFilters">
	    <li class="nav-header">Filter by officer:</li>
                
<?php
    
        foreach ($this->officers as $officer) {
	    echo '<li><a class="filterByOfficer" storyofficer="'.$officer['officer'].'" href="javascript: return false;"><i class="icon-user"></i> '.$officer['officer'].'</a></li>';
	}
        
?>
            
	    <li class="nav-header">Filter by status:</li>
	    <li><a href="javascript: return false;" class="filterByStatus" filterstatus="0"><i class="icon-tag"></i> <?php echo $statuses[0]; ?></a></li>
	    <li><a href="javascript: return false;" class="filterByStatus" filterstatus="1"><i class="icon-ok-sign"></i> <?php echo $statuses[1]; ?></a></li>
	    <li><a href="javascript: return false;" class="filterByStatus" filterstatus="2"><i class="icon-ok"></i> <?php echo $statuses[2]; ?></a></li>
	    <li><a href="javascript: return false;" class="filterByStatus" filterstatus="3"><i class="icon-lock"></i> <?php echo $statuses[3]; ?></a></li>
	    <li><a href="javascript: return false;" class="filterByStatus" filterstatus="4"><i class="icon-retweet"></i> <?php echo $statuses[4]; ?></a></li>
	</ul>
	<ul class="nav nav-list" style="padding-top:8px">
	    <li class="nav-header">Other options:</li>
	    <li><a href="javascript: return false;" class="resetFilters">&rarr; reset all filters</a></li>
	    <li><a href="javascript: return false;" class="refreshStories">&rarr; refresh stories list</a></li>	    
	</ul>	
    </div>
    
    <div class="span10">
        
<?php

    $this->myCustomTitle = "Stories list";

    if (!$this->stories) { 
        
    // greeting message to those who didn`t created any stories yet
        
?>
        
          <div class="alert fade in">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <strong>Hi there!</strong> You have not created any stories yet, but you can do so by pressing a button below!
          </div>
        
<?php

    } else {
        
    // render stories list
        
        foreach ($this->stories as $story) {

            $subtitle = 'Author: '.$story['content']['author'].' | Officer: '.$story['content']['officer'];
            $commentsCount = count($story['comments']);
            $currentStatusTitle = 'Mark as Started';
	    $storyID = $story['content']['id'];

            echo '<div class="alert alert-info story" storyStatus="'.$story['content']['status'].'" storyOfficer="'.$story['content']['officer'].'" storyID="'.$story['content']['id'].'">';
            echo '<div class="storyBlock"><div class="storyBlockTitle"><h4><strong>['.$statuses[$story['content']['status']].'] #'.$storyID.'</strong> '.$story['content']['title'].'</h4></div>';
            echo '<p>'.$subtitle.'</p><p>Description: '.$story['content']['desc'].'</p>';

            ?>

            <div class="storyBlockRight">
		
                <div class="btn-group">
		    
<?php
	    $markAsStartedDisabled = '';
	    $markAsFinishedDisabled = '';
	    $markAcceptRejectDisabled = '';
	    
	    if ($story['content']['author'] != $this->userInfo->username) {
		    $markAcceptRejectDisabled='disabled';
	    }	
	    if ($story['content']['officer'] != $this->userInfo->username) {
		    $markAsStartedDisabled='disabled';
		    $markAsFinishedDisabled='disabled';
	    }
	    
	    switch ($story['content']['status']) {
		 case 0: 
		    echo '<a class="btn setStoryStatus '.$markAsStartedDisabled.'" href="javascript: return false;" statusToBeSet="1" storyID="'.$storyID.'">Mark as started</a>';
		    break;
		 case 1: 
		    echo '<a class="btn setStoryStatus '.$markAsFinishedDisabled.'" href="javascript: return false;" statusToBeSet="2" storyID="'.$storyID.'">Mark as Finished</a>';
		    break;
		 case 2: 
		    echo '<a class="btn acceptRejectStory '.$markAcceptRejectDisabled.'" href="javascript: return false;" statusToBeSet="3" storyID="'.$storyID.'">Accept / Reject</a></a>';
		    break;
		 case 3: 
		 case 4:     
		    echo '<a class="btn disabled href="javascript: return false;">story commands</a></a>';
		    break;	
	    }
?>
                    
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript: return false;" class="editStory" storyID="<?php echo $storyID; ?>"><i class="icon-pencil"></i> Edit Story</a></li>			
                        <li><a href="javascript: return false;" class="deleteStory" storyID="<?php echo $storyID; ?>"><i class="icon-remove"></i> Delete Story</a></li>
                    </ul>
                </div>
                <a class="btn commentbutton tooltiped" data-original-title="Toggle comments (<?php echo $commentsCount; ?>)" data-toggle="button"><i class="icon-comment"></i></a>
            </div>

        </div>
      
        <div class="storyComments">
            

<?php

            foreach ($story['comments'] as $comment) {
                echo '<pre id="cmt'.$comment['id'].'">'.$comment['author'].' wrote: '.$comment['text'].'<a class="removeComment" title="Delete Comment" href="#" commentID="'.$comment['id'].'">×</a></pre>';
            }

?>
            
            <textarea class="input-xlarge" id="commentTextarea<?php echo $storyID; ?>" rows="2"></textarea>
            <a class="btn addCommentBtn" storyID="<?php echo $storyID; ?>">Add comment</a>
        </div>


    </div>

<?php

        }

        
    }
?>

<a class="btn btn-primary" id="storyAdd" href="javascript: return false;">Add new story</a>